name: binder-env

channels:
  - conda-forge

dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - pdal
  - ca-certificates=2026.6.17
  - certifi=2026.6.17
  - pyspark
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pyarrow
  - polars
  - laspy
  - plotly
  - bokeh
  - trimesh
  
  - pip

  # Pip-Pakete
  - pip:
      - -r requirements.txt
