name: binder-env

channels:
  - conda-forge

dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - pdal
  - pyspark
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pyarrow
  - polars
  - laspy
  - plotly
  - bokeh
  - trimesh
  
  - pip

  # Pip-Pakete
  - pip:
      - -r requirements.txt
